version: 0.2

env:
  parameter-store:
    NPM_TOKEN: npmjs_publish

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn build
      - yarn test
  post_build:
    commands:
      - echo Build completed on `date`
      - yarn version --patch

artifacts:
  files:
    - dist/*
    - package.json
    - node_modules/*