version: 0.2

env:
  variables:
    GIT_REPO: "github.com/XYOracleNetwork/tool-domains-nodejs"
    BRANCH_NAME: "master"
    GIT_USER: "arietrouw"
  parameter-store:
    NPM_TOKEN: npmjs_publish
    GIT_TOKEN: github_pipeline

phases:
  install:
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - apt-get update -y
      - apt-get install -y yarn
      - git clone -b $BRANCH_NAME https://$GIT_USER:$GIT_TOKEN@$GIT_REPO
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn build
      - yarn test
  post_build:
    commands:
      - echo Build completed on `date`
      - yarn version --patch

artifacts:
  files:
    - dist/*
    - package.json
    - node_modules/*